const express = require("express")
const interviewRouter = express.Router()
const userAuthMiddleware = require("../middlewares/auth.middlewares")
const upload= require('../middlewares/file.middleware')
const interviewReportController = require('../controller/interview.controller')


/**
 * @route api/interview/
 * @description  generating interview report from AI by Gemini model
 * @access private
 */
interviewRouter.post('/',userAuthMiddleware.authUser,upload.single("resume"),interviewReportController.interviewReportController)


/**
 * @route api/interview/report/:interviewId
 * @description Showing specific report to the user by the Report Id 
 * @access private
 */

interviewRouter.get('/report/:interviewId',userAuthMiddleware.authUser,interviewReportController.getinterviewReportbyIdController)


/**
 * @route api/interview/
 * @description Get all the report generated by the user 
 * @access private
 */

interviewRouter.get('/',userAuthMiddleware.authUser,interviewReportController.getAllInterviewReportController)


/**
 * @route api/interview/resume/:interviewId
 * @description Generating ATS friendly resume by the AI 
 * @access private
 */

interviewRouter.post('/resume/pdf/:interviewReportId',userAuthMiddleware.authUser,interviewReportController.generateResumePdfController)


module.exports=interviewRouter